name: Docker Build

# 触发条件：每次 push 时
on:
  push:
    branches:
      - main  # 或者你希望的分支名

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出当前代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 设置 Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 设置 Docker 缓存
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # 给脚本加执行权限
      - name: Grant execute permission for docker.sh
        run: chmod +x ./docker.sh

      # 运行 docker build
      - name: Run docker build
        run: docker build -t ruiji-takeout .

      # 运行docker容器
      - name: Run docker container
        run: docker run --rm --name ruiji -p 8081:8080 ruiji-takeout /bin/bash -c "echo 'Container ran successfully and is now stopping.'"

      # 验证 docker build 成功
      - name: Verify Docker build
        run: |
          if [ $? -eq 0 ]; then
            echo "Docker build successful!"
          else
            echo "Docker build failed."
            exit 1
          fi
